### ISSUE TITLE
Similarity calculation algorithm

### ISSUE THREAD

**Issue by gunwooterry** [glossm/api#14]
새로운 답안이 제출되었을 때 기존 답안들과의 유사도를 비교하여 점수를 책정해야 합니다.
두 string의 distance를 측정하는 대표적인 알고리즘 2개를 소개합니다.

### [Levenshtein distance](http://www.wikiwand.com/en/Levenshtein_distance)
A를 B로 만들기 위해 필요한 최소 insertion/deletion/substitution의 횟수입니다.
즉, **star**와 **start**의 Levenshtein distance는 1입니다.
계산하는 데 시간이 오래 걸린다는 단점이 있습니다.

### [Cosine similarity](http://www.wikiwand.com/en/Cosine_similarity)
문자열 A와 B를 모두 vector로 변환하여, 두 vector의 cosine similarity를 구합니다.
계산 속도가 빠르다는 장점이 있으나, 단어 내에서의 순서를 고려하지 않는 문제가 있습니다.
즉, **hello**와 **olleh**의 유사도를 100%로 측정합니다.

두 알고리즘 모두 Glossm에서 바로 사용하기에는 부적합하며, 새로운 알고리즘을 찾든지 적절히 조합/변형하여 사용하여야 할 것 같습니다.

**Comment by mnkykm** [comment]
별 고민없이 Levenshtein distance 를 생각하고 있었습니다. 
유저 입장에서 자신의 점수가 개별 음소별(글자별)로 채점된다는 것이 훨씬 직관적이라고 생각했기 때문입니다.
유저가 전사 submission 1개를 제출하면, 그것을 비교할 다른 submission 의 개수는 많아야 수십개 입니다. 
이게 속도가 많이 오래 걸릴까요? 어떻게 생각하시는지요.
매 전사 제출 당시에 점수를 계산해서 부여하고, 
다른 사람이 새로 해당 단어에 제출했을 때는 기존 제출자들이 받은 점수에는 변동이 없게 하면 큰 무리가 없을 것 같다는 생각입니다.

**Comment by mnkykm** [comment]
비교할 다른 제출 답안의 개수가 너무 많아지면, 상위 N개와의 비교만을 하는 제한을 거는 방법도 있겠습니다.

**Comment by gunwooterry** [comment]
생각해보니 우리 scale에서는 체감할 만한 차이가 많이 안 느껴질 것 같네요.
일단 구현해 보고 문제가 있으면 그 때 가서 해결해도 될 것 같습니다.
