### ISSUE TITLE
TopicSet, Topic need designated codes

### ISSUE THREAD

**Issue by mnkykm** [glossm/api#35]
Topic 또는 Meaning 을 csv import 하는 과정에서 TopicSet 또는 Topic 의 번호를 알 수 없어 csv 파일을 계속 수정해야 하는 필요가 있습니다. TopicSet 또는 Topic 도 Meaning 필드의 `ask_code` (e.g. `vx001`) 또는 Language 필드의 `code` (e.g. `bak`)와 같이 우리가 지정해줄 수 있는 Unique 한 code 데이터가 필요할 것 같습니다. 둘 다 char(5) 정도면 괜찮을 것 같습니다.

**Comment by gunwooterry** [comment]
1. CSV import 시에 TopicSet과 Topic의 `id`를 알아야 하는 문제
2. Unique한 code가 필요함

두 가지의 문제는 일단 독립적인 것으로 보이는데, `TopicSet`-`Topic`-`Meaning`의 관계를 설정하려면 import 시에 related field 정보를 주어야 합니다. 우리가 이미 가지고 있는 정보가 아니라면 반드시 필요한 게 아니라면 임의로 추가할 필요는 없다고 생각합니다.
또한 import 시에 유일성을 확인하는 `import_id_fields`는 복수로 설정할 수도 있습니다.

**Comment by mnkykm** [comment]
정보를 임의로 추가하지 않은 것은 좋지만 현재 개발 과정에서 data 를 서로 다른 database 에서 import 하거나 DB 를 리셋할 때, 데이터를 export 해서 각 Topic Set 와 Topic 의 번호를 찾고 이에 따라 Meaning csv 에서 Topic 의 번호를 수정해야 하는 번거로움이 있습니다. 이들이 모두 1부터 시작해서 순차적으로 올라가는 수면 좋을텐데, 이유를 모르겠지만 DB 를 전부 삭제하고 처음 import 한 행이 2로 시작하거나, 내가 import 한 csv의 행 순서와 반대로 숫자가 매겨지거나 하는 등 그 숫자를 예측하기가 어렵습니다.

**Comment by gunwooterry** [comment]
무슨 뜻인지 알겠습니다. 추가하는 게 좋을 것 같네요. 구현하겠습니다.

**Comment by mnkykm** [comment]
Topic 의 고유 번호가 생겼으므로, Topic 의 FK 로서 unique 한 TopicSet 이 필요없지 않을까 합니다. 예를 들어, 같은 Topic 인 기상, 계절, 신체부위가 있을때 TopicSet을 여러개 만들어 누구에겐 기상-계절-신체부위 순으로 누구에게는 계절-신체부위-기상 순으로 누구에게는 신체부위-기상-계절 순서로 제공하는 등의 베리에이션을 만들 수 있지 않을까요?
