### ISSUE TITLE
Divide Language into Courses

### ISSUE THREAD

**Issue by mnkykm** [glossm/api#43]
<img width="724" alt="2018-06-22 10 02 36" src="https://user-images.githubusercontent.com/26748682/41752610-72a7eb14-7603-11e8-9edb-4dba5869ec09.png">
어휘 항목별로 정리한 Meaning 개수입니다.
파란색이 쉬운 단어 (1등급, 2등급) 주황색이 어려운 단어 (3등급, 4등급)입니다.
약 3천개에 달하는 단어를 모두 한 테크트리에 담는 것은 부담으로 다가올 수 있을 것 같아,
각 언어를 3개 정도의 레벨로 쪼개는 것을 제안합니다.
예를 들어, 언어 선택 화면에서 Bashkir (beginner), Bashkir (intermediate), Bashkir (advanced)
이렇게 선택할 수 있으면 좋을 것 같습니다.

이를 위해서 Language 모델에 level (char) 항목을 추가하고,
(iso_code, level) 튜플로 unique key 를 주는 게 어떨까요?

**Comment by mnkykm** [comment]
- Bashkir (beginner)
- Bashkir (intermediate)
- Bashkir (advanced)

이것들을 Bashkir 라는 **Language** 하위에 있는 **Course** 라는 단위로 모델을 짜는게 어떨까 합니다.

제가 일을 복잡하게 만드는게 아닐지 걱정이 되는데, 
만약 그렇다면 일단 베타 런칭에는 beginner 코스만 올리는 걸 목표로 하고 
그 뒤에 장기적으로 생각할 수도 있을 것 같네요.

**Comment by gunwooterry** [comment]
저는 Course라는 새로운 모델을 만드는 것에 약간 회의적입니다. 데이터의 복잡도를 불필요하게 올린다는 느낌입니다.
사용자가 느끼는 심리적 장벽을 낮추고자 하는 게 주 목적인 것 같은데, 이건 language 내에서 마일스톤을 설정하고, 이 마일스톤들을 성취하도록 유도하는 인터페이스를 디자인하는 게 더 효율적이고 근본적인 해결책이 아닐까 싶습니다.

개인적으로는 언어 선택 창에 beginner, intermediate, advanced 같은 게 적혀 있으면 처음 사용할 때에는 상당히 혼란스러울 것 같다는 느낌입니다.

**Comment by mnkykm** [comment]
그것도 좋은 생각이네요. 
예를 들어, Beginner 단계의 단어들 학습이 모두 끝나면 Language 아이콘이나 화면 색깔이 바뀜으로서 단계가 올랐다는 것을 알 수 있으면 좋을 것 같습니다.
다만, Topic Set 를 어떻게 분할해야 할것인지에 대해 데이터 구조를 생각해주시면 좋겠습니다.

**Comment by gunwooterry** [comment]
TopicSet 분할에 대한 이슈가 어디선가 한 번 나온 것 같은데 기억이 잘 안 나네요.
다시 한 번 말씀해주시거나 Github 상에서 오갔던 이야기면 reference 부탁드립니다.

**Comment by mnkykm** [comment]
요 이슈 닫고 새롭게 올리겠습니다. 
고민해 봤는데 일단 베타 런칭때는 비기너 수준 단어만 업로드하는 걸 목표로 하고 레벨 분할에 대한 생각은 후순위로 미루겠습니다.
